### ISSUE TITLE
Signature of `rand`

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/ManifoldMeasures.jl#12]
While we were discussion the allocations of rand (we could continue this maybe also here) I noticed one design difference I would like to mention / discuss.

Usually we have as (one of the) first parameters the manifold

For the measures we now have the manifold as a field. Is that necessary? Or is maybe the manifold as a parameter somewhere too complicated?

In accordance with `ManifoldsBase` I would like maybe something like

`rand(rng, M, d)` or if you want to also provide the point type(T) or a point the result should be similar to `rand(rng,M,T,d)` ar `rand(rng, M, p, d)` for a `distribution `d`.
Similarly `rand!(rng, M, p, d)` would work in place of `p`

The distribution then does not have to know on which manifold it lies but every function working on it would get `M`as a first parameter.

What do you think?

**Comment by sethaxen** [comment]
> For the measures we now have the manifold as a field. Is that necessary? Or is maybe the manifold as a parameter somewhere too complicated?

> The distribution then does not have to know on which manifold it lies but every function working on it would get `M`as a first parameter.

One of the purposes of ManifoldMeasures.jl is to extend MeasureTheory.jl to support measures on manifolds. To that end, when we overload a function also overloaded by MeasureTheory, the arguments should be similar, so that our measures can be used interchangeably with theirs, and so that packages like PPLs that support MeasureTheory automatically work with our measures.

So what we want to avoid is signatures like `logdensity(M, d, x)` or `rand(rng, M, d)` which would be the Manifolds way. But we do need to customize the density computation and sampling for a given manifold, so we have to store a copy of the manifold in the measure. But there's precedence for this in Manifolds. Not only manifold decorators but also subtypes of `AbstractGroupAction` store the manifold.

How `rand` will be implemented in MeasureTheory.jl is not yet decided (see https://github.com/cscherrer/MeasureTheory.jl/issues/129), and FWIW, we currently are here using https://github.com/cscherrer/MeasureTheory.jl/issues/129#issuecomment-894346507. But this is more convenience and can change at any time. Part of living on the bleeding edge.

**Comment by sethaxen** [comment]
Also, related to random point generation, which I know is an interest of yours, we may want something like this:

```julia
default_measure(M) = Hausdorff(M)
default_probability_measure(M) = normalize(default_measure(M))
default_sampleable_measure(M) = default_probability_measure(M)
```

We could go one step further to define
```julia
Base.rand(rng::AbstractRNG, M::AbstractManifold) = rand(rng, default_sampleable_measure(M))
```
but I think this could introduce bugs if a user expects `rand(M)` to generate a uniformly sampled point.

**Comment by kellertuer** [comment]
> But there's precedence for this in Manifolds. Not only manifold decorators but also subtypes of `AbstractGroupAction` store the manifold.

sure, they have to store it, that was also what I was asking for and – thanks for the explanation – it seems we have to go the store-it-way here, then.

**Comment by kellertuer** [comment]
> Also, related to random point generation, which I know is an interest of yours, we may want something like this:
> 
> ```julia
> default_measure(M) = Hausdorff(M)
> default_probability_measure(M) = normalize(default_measure(M))
> default_sampleable_measure(M) = default_probability_measure(M)
> ```
> 
> We could go one step further to define
> 
> ```julia
> Base.rand(rng::AbstractRNG, M::AbstractManifold) = rand(rng, default_sampleable_measure(M))
> ```
> 
> but I think this could introduce bugs if a user expects `rand(M)` to generate a uniformly sampled point.

This looks nice overall, but I can not answer the last point, since I am not experienced enough on measures there.

**Comment by kellertuer** [comment]
Since I understood why we switch the signature, this can be closed. I might look after the methods are available whether a default `rand(M)` or `rand(M,p)` (for tangents) might be doable/useful.
